baseURL = "http://localhost/"
languageCode = "en-us"
title = "Baltimore Black Techies"
theme = ['alpha-church']
# themesDir = "../.."

enableEmoji = true

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[taxonomies]
  tag = "tags"
  preacher = "preachers"
  series = "series"

#This theme can generate a multi-level theme.
#Use the weight= to specify the order of menu items, and the parent= to create a submenu item.
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 2

  [[menu.main]]
    name = "About Us"
    parent = "About"
    url = "/about"
    weight = 1

  [[menu.main]]
    name = "Leaders"
    parent = "About"
    url = "/leaders"
    weight = 2

  [[menu.main]]
    name = "Resources"
    url = "#"
    weight = 3

  [[menu.main]]
    name = "Blog"
    url = "/posts"
    parent = "Resources"
    weight = 2

  [[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 4

# Paramaters for the whole site
[params]
  title = "Baltimore Black Techies"
  subtitle = "Building Tech and Community in Baltimore City"
  author = "Baltimore Black Techies"

  customCSS = ["custom.css"]

  [params.map]
    # For Open Street Map widgets
    latitude = "39.31136"
    longitude = "-76.61569"
    zoom = "18"

  [params.contact]
    #Use this section to automate contact form.
    #Set service to either "netlify" or "formspree"
    #For formspree, please setup an account at https://formspree.io/
    #For netlify, please read https://www.netlify.com/docs/form-handling/
    #
    #If you use netlify, you'll need to set the confirm_page value (or elase users will see a generic netlify response)
    #If you use formspree, you'll need to set your formspree email address.
    service = "netlify"
    confirm_page = "/contact_thanks"
    # formspree_email=""

  #Paramaters for the home/landing page
  [params.landing]

    [params.landing.banner]
      image = "img/bbtechies.jpg"

      [[params.landing.banner.button]]
        url = "/contact"
        text = "Get in touch"
        type = "special"

        [[params.landing.banner.button]]
        url = "#feature-icons"
        text = "Find out more"

    #Details for the box below the banner
    [params.landing.services]
      title = "Building Tech and Community in Baltimore City"
      text = "We meet 6:30 PM every Thursday at The Impact Hub [10 E North Ave Baltimore, MD 21202](http://baltimore.impacthub.net/)."
      map_location = "Impact Hub"

    [params.landing.feature_heading]
      title = "We operate four different nights on a rotating schedule:"
    [params.landing.feature_icons]
      #These feature icons look best if there's an even number of them.
      enable = true

      #Accent is a colour defined in the CSS file. Choose between 1 and 5
      [[params.landing.feature_icons.tile]]
        icon = "fa-comments"
        icon_pack = "fas"
        accent = "5"
        title = "Speaker Night"
        text = "On speaker night we feature either guest speakers or our very own members who want to present on a particular topic."

      [[params.landing.feature_icons.tile]]
        icon = "fa-hands-helping"
        icon_pack = "fas"
        accent = "1"
        title = "Social Night"
        text = "Socializing, networking, and getting to know your peers is always a part of the successful professional development process!"

      [[params.landing.feature_icons.tile]]
        icon = "fa-laptop-code"
        icon_pack = "fas"
        accent = "2"
        title = "Project Night"
        text = "On project nights, we dive head first into the projects in which we are most interested."

      [[params.landing.feature_icons.tile]]
        icon = "fa-terminal"
        icon_pack = "fas"
        accent = "3"
        title = "Study Group Night"
        text = "Study group night is an opportunity for the group to collaborate on projects or share ideas."

    [params.landing.feature_images]
      #These feature images look best if there's an even number of them.
      enable = true

      [[params.landing.feature_images.tile]]
        image = "img/freely-10057.jpg"
        title = "Black Techies"
        text = ""
        url = ""
        button_text = "Learn more"

      [[params.landing.feature_images.tile]]
        image = "img/freely-26905.jpg"
        title = "Slack Channel"
        text = "Do you want to join our slack channel?"
        url = "#"
        button_text="Join our Slack"

    [params.landing.CTA]
      heading = "Get in touch!"
      message = "We'd love to hear from you."

    [params.footer]
      copyright = ["© Baltimore Black Techies. All Rights Reserved",
                  ]

    [[params.links]]
      service = "Meetup"
      icon = "fa-meetup"
      icon_pack = "fab"
      link = "//meetup.com/Baltimore-Black-Techies-Meetup"

    [[params.links]]
      service = "Twitter"
      icon = "fa-twitter"
      icon_pack = "fab"
      link = "//twitter.com/"

    [[params.links]]
      service = "Facebook"
      icon = "fa-facebook"
      icon_pack = "fab"
      link = "//facebook.com/bmoreblacktechies"
